# Generated by Django 5.0 on 2024-04-07 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='size_object',
            field=models.ManyToManyField(to='shop.size'),
        ),
    ]
