# Generated by Django 5.0.1 on 2024-04-08 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_product_size_object'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pin',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
